[custom.all.promise]
type = "github"
url  = "https://github.com/kbertalan/tyttp"
commit = "extract-promise"
ipkg = "tyttp.ipkg"

[custom.all.promise]
type = "github"
url  = "https://github.com/kbertalan/idris2-promise"
commit = "main"
ipkg = "promise.ipkg"
